name: AuthApi.WebApi.GoogleAppEngine CI
on:
  push:
    branches:
      - main
    paths:
      - 'AuthApi.WebApi.GoogleAppEngine/**'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CONFIG: Release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: production config
        uses: microsoft/variable-substitution@v1
        with:
          files: 'AuthApi.WebApi.GoogleAppEngine/AuthApi/appsettings.json'
        env:
          ApiKey: ${{ secrets.AUTHAPI_API_KEY }}
          Database.GoogleProject: ${{ secrets.AUTHAPI_DATABASE_GOOGLEPROJECT }}
          Database.CollectionNameApplications: ${{ secrets.AUTHAPI_DATABASE_COLLECTIONNAMEAPPLICATIONS }}
          Database.CollectionNameAccounts: ${{ secrets.AUTHAPI_DATABASE_COLLECTIONNAMEACCOUNTS }}
          Database.CollectionNameRefreshTokens: ${{ secrets.AUTHAPI_DATABASE_CollectionNameRefreshTokens }}
          Jwt.Keys[0].PrivateKey: ${{ secrets.AUTHAPI_JWT_KEYS_PRIVATEKEY }}
          Jwt.Keys[0].PublicKey: ${{ secrets.AUTHAPI_JWT_KEYS_PUBLICKEY }}
          Jwt.Keys[0].Version: 1
          Jwt.KeyVersion: 1
          Jwt.MaxRefreshCount: 5
          DatabaseInit: ${{ secrets.AUTHAPI_DATABASEINIT }}          
      - name: nuget source
        run: dotnet nuget add source --username MichaelDiers --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MichaelDiers/index.json"
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build --configuration "$CONFIG"
      - name: test
        run: dotnet test --configuration "$CONFIG" --no-build
      - name: publish
        run: dotnet publish -c "$CONFIG"
      - name: deploy google app engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_CREDENTIALS_AUTHAPI }}
          project_id: ${{ secrets.PROJECT_ID_AUTHAPI }}
          working_directory: AuthApi.WebApi.GoogleAppEngine/AuthApi/bin/Release/netcoreapp3.1/publish
          deliverables: app.yaml
defaults:
  run:
    working-directory: 'AuthApi.WebApi.GoogleAppEngine'