name: AuthApi.WebApi.GoogleAppEngine CI
on:
  push:
    branches:
      - main
    paths:
      - 'AuthApi.WebApi.GoogleAppEngine/**'
  workflow_dispatch:
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      CONFIG: Release
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: nuget source
        run: dotnet nuget add source --username MichaelDiers --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/MichaelDiers/index.json"
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build --configuration "$CONFIG"
      - name: test
        run: dotnet test --configuration "$CONFIG" --no-build
defaults:
  run:
    working-directory: 'AuthApi.WebApi.GoogleAppEngine'