name: AuthApi.WebApi.GoogleAppEngine CI
on:
  push:
    branches:
      - main
    paths:
      - 'AuthApi.WebApi.GoogleAppEngine/**'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1
      - name: build
        run: dotnet build --configuration Release      
defaults:
  run:
    working-directory: 'AuthApi.WebApi.GoogleAppEngine'