name: LogApi.GoogleFunctions CI/CD
on:
  pull_request:
    branches:
      - main
    paths:
      - 'LogApi.GoogleFunctions/**'
  push:
    branches:
      - main
    paths:
      - 'LogApi.GoogleFunctions/**'
  workflow_dispatch:
jobs:
  devDeployment:
    runs-on: ubuntu-latest
    environment:
      name: LogApiDevDeployment
    env:
      CONFIG: Release
      CURRENT_ENVIRONEMNT: dev
    steps:      
      - name: checkout source
        uses: actions/checkout@v2
      - name: "config ${CURRENT_ENVIRONEMNT}"
        uses: microsoft/variable-substitution@v1
        with:
          files: 'LogApi.GoogleFunctions/LogApi/appsettings.json'
        env:
          ApiKey: ${{ secrets.API_KEY }}
          MongoDb.CollectionName: ${{ secrets.MONGODB_COLLECTION_NAME }}
          MongoDb.ConnectionStringFormat: ${{ secrets.MONGODB_CONNECTION_STRING_FORMAT }}
          MongoDb.DatabaseName: ${{ secrets.MONGODB_DATABASE_NAME }}
      - name: copy and edit nuget config
        run: |
          mv ../.github/workflows/LogApi.GoogleFunctions-ci-nuget.config LogApi/nuget.config
          echo $(sed -e "s/\${USERNAME}/${{ secrets.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" LogApi/nuget.config) >LogApi/nuget.config
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build --configuration "$CONFIG"
      - name: test
        run: dotnet test --configuration "$CONFIG" --no-build
      - name: google cloud deployment
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: "log-function-${CURRENT_ENVIRONEMNT}"
          runtime: dotnet3
          credentials: ${{ secrets.GCP_CREDENTIALS_AUTHAPI }}
          source_dir: LogApi.GoogleFunctions/LogApi
          entry_point: LogApi.LogFunction  
defaults:
  run:
    working-directory: 'LogApi.GoogleFunctions'