name: LogApi.GoogleFunctions CI/CD
on:
  pull_request:
    branches:
      - main
    paths:
      - 'LogApi.GoogleFunctions/**'
  push:
    branches:
      - main
    paths:
      - 'LogApi.GoogleFunctions/**'
  workflow_dispatch:
jobs:
  devDeployment:
    runs-on: ubuntu-latest
    env:
      CONFIG: Release
    steps:
      - name: checkout source
        uses: actions/checkout@v2
      - name: dev config
        uses: microsoft/variable-substitution@v1
        with:
          files: 'LogApi.GoogleFunctions/LogApi/appsettings.json'
        env:
          ApiKey: ${{ secrets.API_KEY }}
          MongoDb.CollectionName: ${{ secrets.MONGODB_COLLECTION_NAME }}
          MongoDb.ConnectionStringFormat: ${{ secrets.MONGODB_CONNECTION_STRING_FORMAT }}
          MongoDb.DatabaseName: ${{ secrets.MONGODB_DATABASE_NAME }}
