name: Service.Sdk.Database.MongoDatabase Service CI
on:
  push:
    branches:
      - main
    paths:
      - 'Service.Sdk/Service.Sdk.Database.MongoDatabase/**'
  workflow_dispatch:
jobs:
  MongoDatabaseNuget:
    runs-on: ubuntu-latest
    env:
      CONFIG: Release
      PACKAGE_VERSION: "1.1"
      CSPROJ_FOLDER: Service.Sdk.Database.MongoDatabase
      CSPROJ_FOLDER_TESTS: Service.Sdk.Database.MongoDatabase.Tests
      CSPROJ_NAME: Service.Sdk.Database.MongoDatabase
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: copy and edit nuget config to MongoDatabase
        run: |
          cp ../../.github/workflows/Generic-Nuget.config $CSPROJ_FOLDER/nuget.config
          echo $(sed -e "s/\${USERNAME}/${{ secrets.NUGET_USERNAME }}/" -e "s@\${TOKEN}@${{ secrets.GITHUB_TOKEN }}@" $CSPROJ_FOLDER/nuget.config) >$CSPROJ_FOLDER/nuget.config
      - name: copy nuget config to MongoDatabase.Tests
        run: |
          cp $CSPROJ_FOLDER/nuget.config $CSPROJ_FOLDER_TESTS/nuget.config          
      - name: build
        run: dotnet build --configuration "$CONFIG"
      - name: test
        run: dotnet test --configuration "$CONFIG" --no-build
      - name: pack
        run: dotnet pack "$CSPROJ_FOLDER/$CSPROJ_NAME.csproj" -c "$CONFIG" -p:PackageVersion=$PACKAGE_VERSION.$GITHUB_RUN_NUMBER --no-build
      - name: publish
        run: dotnet nuget push "$CSPROJ_FOLDER/bin/$CONFIG/$CSPROJ_NAME.$PACKAGE_VERSION.$GITHUB_RUN_NUMBER.nupkg" --api-key "$SNTB_TOKEN" --source "https://nuget.pkg.github.com/MichaelDiers/index.json"
        env:
          SNTB_TOKEN: ${{ secrets.SNTB_NUGET_CI_TOKEN}}          
defaults:
  run:
    working-directory: 'Service.Sdk/Service.Sdk.Database.MongoDatabase'