name: Services.Sdk CI
on:
  push:
    branches:
      - main
    paths:
      - 'Services/Service.Sdk/**'
  workflow_dispatch:
jobs:
  ServicesSdkNuget:
    runs-on: ubuntu-latest
    env:
      CONFIG: Release
      PACKAGE_VERSION: "1.1"
      CSPROJ: Service.Sdk/Service.Sdk.csproj
      NUPGKG: Service.Sdk/bin/$CONFIG/Service.Sdk
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: use .net core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: build
        run: dotnet build --configuration "$CONFIG"
      - name: test
        run: dotnet test --configuration "$CONFIG" --no-build
      - name: pack
        run: dotnet pack "$CSPROJ" -c "$CONFIG" -p:PackageVersion=$PACKAGE_VERSION.$GITHUB_RUN_NUMBER --no-build
      - name: publish
        run: dotnet nuget push "$NUPKG.$PACKAGE_VERSION.$GITHUB_RUN_NUMBER.nupkg" --api-key "$SNTB_TOKEN" --source "https://nuget.pkg.github.com/MichaelDiers/index.json"
        env:
          SNTB_TOKEN: ${{ secrets.SNTB_NUGET_CI_TOKEN}}          
defaults:
  run:
    working-directory: 'Services/Service.Sdk'